### ISSUE TITLE
Z flag for diff is not supported on macOS

### ISSUE THREAD

**Issue by holmgr** [CatEars/Companion#1]
The Z flag for the diff command line tool is not supported in macOS so the test script does not compile.
Would advice to either remove this flag option, or use some alternative flags to try to achieve a similar solution.
See https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/diff.1.html

**Comment by CatEars** [comment]
Added a quick fix for this. Since it is a bit hard for me to test I made a simple diff. Don't know how well it works out on mac unfortunately tough...
