### ISSUE TITLE
Template assumes <bits/stdc++.h>

### ISSUE THREAD

**Issue by holmgr** [CatEars/Companion#2]
The default template provided assumes that <bits/stdc++.h> is available which it is not on macOS systems.
A simple work-around is to manually add this file by:
1. Going to `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1`
2. Adding a new folder: `bits`
3. Sudo creating a file `stdc++.h` with the contents given [here](https://gist.githubusercontent.com/frankchen0130/9ac562b55fa7e03689bca30d0e52b0e5/raw/247d699694b9d4d4468f094f06f2b41cb1226582/stdc++.h)

Would recommend adding these instructions to the README to add macOS support.

**Comment by CatEars** [comment]
I added this information to the README close to the end

**Comment by anthansson** [comment]
quite sure this doesn't work on M1 macs!
